# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessExpense",
            fields=[],
            options={
                "verbose_name": "business expense",
                "verbose_name_plural": "business expenses",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.expense",),
        ),
    ]
