# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[],
            options={
                "verbose_name": "promo code",
                "verbose_name_plural": "promo codes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketing.coupon",),
        ),
    ]
