# Generated by Django 5.2.12 on 2026-04-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_promocode"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepagePromoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=260)),
                ("body", models.TextField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="homepage_promos/")),
                (
                    "tone",
                    models.CharField(
                        choices=[("cream", "Cream"), ("dark", "Dark")],
                        default="cream",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="emailsubscriber",
            name="landing_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailsubscriber",
            name="referral_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="emailsubscriber",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="emailsubscriber",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="emailsubscriber",
            name="utm_source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="CampaignLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=260)),
                ("body", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="campaign_landing/"),
                ),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=320)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landing_pages",
                        to="marketing.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
