# Generated by Django 5.2.12 on 2026-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("owner", "Owner"),
                    ("operations_manager", "Operations Manager"),
                    ("inventory_manager", "Inventory Manager"),
                    ("fulfillment_staff", "Fulfillment Staff"),
                    ("marketing_manager", "Marketing Manager"),
                    ("content_editor", "Content Editor"),
                    ("customer_support", "Customer Support"),
                    ("fundraising_coordinator", "Fundraising Coordinator"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=40,
            ),
        ),
    ]
