# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[],
            options={
                "verbose_name": "support ticket",
                "verbose_name_plural": "support tickets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("support.ticket",),
        ),
    ]
