# Generated by Django 6.0.4 on 2026-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("new_customers", models.IntegerField(default=0)),
                ("items_sold", models.IntegerField(default=0)),
                (
                    "avg_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("top_product", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "daily summaries",
                "ordering": ["-date"],
            },
        ),
    ]
