# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetricSnapshot",
            fields=[],
            options={
                "verbose_name": "dashboard metric snapshot",
                "verbose_name_plural": "dashboard metric snapshots",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reporting.dailysummary",),
        ),
    ]
