# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[],
            options={
                "verbose_name": "inventory adjustment",
                "verbose_name_plural": "inventory adjustments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockmovement",),
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[],
            options={
                "verbose_name": "inventory item",
                "verbose_name_plural": "inventory items",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockrecord",),
        ),
    ]
