# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[],
            options={
                "verbose_name": "purchase order line",
                "verbose_name_plural": "purchase order lines",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseorderitem",),
        ),
    ]
