# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("slow_living", "Slow Living"),
                    ("ritual_routines", "Ritual-Based Routines"),
                    ("seasonal_reflections", "Seasonal Reflections"),
                    ("brewing_philosophy", "Brewing Philosophy"),
                    ("brand_storytelling", "Brand Storytelling"),
                ],
                default="slow_living",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("unpublished", "Unpublished"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="ritualjournalentry",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
