# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_blogpost_entry_type_blogpost_status_blogpost_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalPost",
            fields=[],
            options={
                "verbose_name": "journal post",
                "verbose_name_plural": "journal posts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.blogpost",),
        ),
    ]
