# Generated by Django 5.2.12 on 2026-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_journalpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("social_handle", models.CharField(max_length=120)),
                ("primary_platform", models.CharField(max_length=80)),
                ("audience_size", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("pitch", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WholesaleInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=180)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("monthly_volume", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
