# Generated by Django 6.0.4 on 2026-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_ambassadorinquiry_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("contact", "Contact"),
                            ("policies", "Policies"),
                            ("brewing_guides", "Brewing Guides"),
                            ("ritual", "Ritual"),
                            ("shop", "Shop / Product List"),
                            ("custom", "Custom Page"),
                        ],
                        default="home",
                        max_length=80,
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Unique slot identifier on that page, e.g. 'hero', 'intro', 'banner_1'.",
                        max_length=80,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Admin-facing name shown in the portal.",
                        max_length=200,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="HTML content. Use basic tags: &lt;p&gt;, &lt;h2&gt;, &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;, &lt;ul&gt;, &lt;li&gt;, &lt;img&gt;.",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="content_blocks/")),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first when multiple blocks share the same section.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "content block",
                "verbose_name_plural": "content blocks",
                "ordering": ["page_key", "sort_order", "section_key"],
            },
        ),
    ]
