# Generated by Django 6.0.4 on 2026-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_contentblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ImageField(blank=True, upload_to="pages/"),
        ),
        migrations.AddField(
            model_name="page",
            name="image_alt",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
