# Generated by Django 6.0.4 on 2026-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="Single Origin Society", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Quiet luxury for the intentional palate",
                        max_length=300,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello@singleoriginsociety.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(default="US", max_length=100)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=75, max_digits=8),
                ),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Settings",
                "verbose_name_plural": "Business Settings",
            },
        ),
    ]
