# Generated by Django 6.0.4 on 2026-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("express", "Express"),
                    ("overnight", "Overnight"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
