# Generated by Django 6.0.4 on 2026-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="acidity_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="aroma_profile",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="blend_info",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="body_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="finish_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="grind_options",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="is_subscription_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="ritual_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="steeping_notes",
            field=models.TextField(blank=True),
        ),
    ]
