# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_acidity_profile_product_aroma_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewingguide",
            name="audience_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner-Friendly"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brewingguide",
            name="guide_type",
            field=models.CharField(
                choices=[
                    ("pour_over", "Pour-Over"),
                    ("french_press", "French Press"),
                    ("espresso_basics", "Espresso Basics"),
                    ("tea_steeping", "Tea Steeping"),
                    ("matcha_preparation", "Matcha Preparation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="brewingguide",
            name="is_premium_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brewingguide",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="origin",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="pairings",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="style_notes",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tastingnote",
            name="tags",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
