# Generated by Django 5.2.12 on 2026-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_tags_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrewGuide",
            fields=[],
            options={
                "verbose_name": "brew guide",
                "verbose_name_plural": "brew guides",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.brewingguide",),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.category",),
        ),
    ]
