# Generated by Django 5.2.12 on 2026-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brewguide_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="og_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="product",
            name="og_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
